"""Strands tools used by Catalyst analyzer agents."""

from src.agents.tools.db_fetch import (
    fetch_all_analyses,
    fetch_all_artist_analyses,
    fetch_instagram_artist_historic,
    fetch_instagram_artist_stats,
    fetch_instagram_track_historic,
    fetch_instagram_track_stats,
    fetch_spotify_artist_historic,
    fetch_spotify_artist_stats,
    fetch_spotify_track_historic,
    fetch_spotify_track_stats,
    fetch_tiktok_artist_historic,
    fetch_tiktok_artist_stats,
    fetch_tiktok_track_historic,
    fetch_tiktok_track_stats,
    fetch_top5_instagram_videos,
    fetch_top5_tiktok_videos,
    fetch_top5_youtube_shorts,
    fetch_top5_youtube_videos,
    fetch_youtube_artist_historic,
    fetch_youtube_artist_stats,
    fetch_youtube_track_historic,
    fetch_youtube_track_stats,
)
from src.agents.tools.period import (
    calendar_anchors,
    fetch_track_basics,
    today_info,
)
from src.agents.tools.video import analyze_video

__all__ = [
    "fetch_all_analyses",
    "fetch_all_artist_analyses",
    "fetch_instagram_artist_historic",
    "fetch_instagram_artist_stats",
    "fetch_instagram_track_historic",
    "fetch_instagram_track_stats",
    "fetch_spotify_artist_historic",
    "fetch_spotify_artist_stats",
    "fetch_spotify_track_historic",
    "fetch_spotify_track_stats",
    "fetch_tiktok_artist_historic",
    "fetch_tiktok_artist_stats",
    "fetch_tiktok_track_historic",
    "fetch_tiktok_track_stats",
    "fetch_top5_instagram_videos",
    "fetch_top5_tiktok_videos",
    "fetch_top5_youtube_shorts",
    "fetch_top5_youtube_videos",
    "fetch_youtube_artist_historic",
    "fetch_youtube_artist_stats",
    "fetch_youtube_track_historic",
    "fetch_youtube_track_stats",
    "fetch_track_basics",
    "today_info",
    "calendar_anchors",
    "analyze_video",
]
